[package]
name = "nacho_basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
ordered-float = "4.1.0"

[profile.dev]
opt-level = 0
debug = true